### ISSUE TITLE
Github pages compability

### ISSUE THREAD

**Issue by lordpansar** [keithmifsud/jekyll-target-blank#27]
Hi!

This plugin is exactly what I'm looking for, but it doesn't seem to be compatible with Github pages? If I'm wrong, please neglect this issue report.

**Comment by keithmifsud** [comment]
Hi @lordpansar I'm glad you like this plugin. Unfortunately, so far, GH pages only allow plugins that they have developed in-house. I did request that they do include this plugin but they have not actioned it yet. I don't think they will anytime soon.

Your alternatives are to sue a different host, such as Netlify or Firebase etc..

**Comment by maslyankov** [comment]
https://jamiegoodwin.uk/seo-friendly-nofollow-links-jekyll-github-pages/ <- Solution
