### ISSUE TITLE
How to exclude certain addresses from the plugin processing?

### ISSUE THREAD

**Issue by simptomy-i-lechenie** [keithmifsud/jekyll-target-blank#37]
Hello.
How to exclude certain addresses from the plugin processing?
like this:
```
Exclude:
     true
site:
     example.com
```

**Comment by keithmifsud** [comment]
Thank you for your question. Unfortunately, this library does not offer functionality to exclude a domain. However, you can currently work in inverse. You can configure the plugin to only open external links in a new tab if they have a certain css class as detailed n this section: https://github.com/keithmifsud/jekyll-target-blank#override-the-default-behaviour

If you still need to exclude an entire domain, please open a new issue and label it as an enhancement. I will develop the feature based on common demand. You're also welcome to contribute to the project and submit your PR.
