### ISSUE TITLE
Update for Jekyll 4

### ISSUE THREAD

**Issue by souldanger** [keithmifsud/jekyll-target-blank#40]
Hello
would you mind updating dependencies to the latest Jekyll?
The current release does not work with Jekyll 4, unfortunately.

Keep up the great work & thanks a bunch!

**Comment by Krinkle** [comment]
Ref https://github.com/keithmifsud/jekyll-target-blank/pull/35

**Comment by keithmifsud** [comment]
Hi @souldanger just now reviewing the PR by @Krinkle and will release v2.0 shortly (today). Sorry for my lateness and massive thank you to Krinkle :heart:

**Comment by souldanger** [comment]
Excellent - very, very much appreciated!
All hail Krinkle and yourself of course... :-)
