### ISSUE TITLE
1.2.0 doesn't work with Jekyll v4

### ISSUE THREAD

**Issue by souldanger** [keithmifsud/jekyll-target-blank#43]
Hi Keith,
latest version doesn't work with Jekyll v4, which seems to be a rubocop issue...
Built a local version requiring rubocop-jekyll instead and it seems to work just fine.
Would be absolutely fantastic if you could do the same.
Cheers!

**Comment by keithmifsud** [comment]
Hi Michael,

sorry, I didn't manage to release v2.0 yesterday. I'll do today..

v1.2 is a security fix and v2 is forJekyll 4. Also with th security fix :)

**Comment by souldanger** [comment]
Splendid - love your work!

**Comment by keithmifsud** [comment]
Hi Michael, I released v2.0. Please don't hesitate to report any issues. Thank you for your help (and for pushing me to release it it :smile: )
