### ISSUE TITLE
In 2.0.0: undefined method `match?' for "/":String (NoMethodError)

### ISSUE THREAD

**Issue by nitrocode** [keithmifsud/jekyll-target-blank#48]
Hello. I noticed that after this module's 2.0.0 version gem was released, my Jekyll builds started to fail on this error. When I run it with `--trace` it points to this gem with the following error message.

```
✗ bundle exec jekyll build -d public --trace
Configuration file: /home/user/git/gitlab/myname.gitlab.io/_config.yml
            Source: /home/user/git/gitlab/myname.gitlab.io
       Destination: public
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
/home/user/git/gitlab/myname.gitlab.io/vendor/bundle/ruby/2.3.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:195:in `external?': undefined method `match?' for "/":String (NoMethodError)
Did you mean?  match
	from /home/user/git/gitlab/myname.gitlab.io/vendor/bundle/ruby/2.3.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:92:in `processable_link?'
	from /home/user/git/gitlab/myname.gitlab.io/vendor/bundle/ruby/2.3.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:78:in `block in process_anchor_tags'
```

Is this line [jekyll-target-blank#L195](https://github.com/keithmifsud/jekyll-target-blank/blob/master/lib/jekyll-target-blank.rb#L195) parsable by ruby 2.3.x ?

The previous versions 1.2 and 1.1.1 seemed to work as expected.

**Comment by keithmifsud** [comment]
Hi @nitrocode ..sorry..I did not notice your message. Are you sure you're using the correct version of JTB with your Ruby version? I think you should revert back to version 1.xx .. you won't lose any features, both versions have all the features.

**Comment by nitrocode** [comment]
I didn't realize that the ruby version I was using was unsupported. I'll upgrade my ruby to a later version when I have time and pin the gem back to 1.x until then. Thank you.
