### ISSUE TITLE
css tag for *not* modifying external links

### ISSUE THREAD

**Issue by jmankoff** [keithmifsud/jekyll-target-blank#49]
According to the documentation, it is possible to set jekyll-target-blank up so that no external links are assigned target=blank without a css tag, but what about the reverse: all external links EXCEPT those with a specific css tag? Sorry if I missed this and it is supported!

**Comment by keithmifsud** [comment]
Hi @jmankoff,

Thanks for asking and wish you a happy new year.

No, the inverse is not supported. However, you are welcome to submit a PR if you need this. I'll be happy to review and merge the code if needed.

**Comment by jmankoff** [comment]
I do need it but haven't had a chance to implement. Thanks for the response.
