### ISSUE TITLE
Make the plugin work with Markdown only

### ISSUE THREAD

**Issue by xplosionmind** [keithmifsud/jekyll-target-blank#56]
When I write the `<a>` tags in HTML, often times I need to specify different and custom `rel` attributes. It would be great if we could select in `_config.yml` if the plugin should work only with Markdown links or in all the website, regardless if the link is in md or HTML.

Something like this could be implemented in `_config.yml`:

```yaml
target-blank:
  md-only: true # or “false” (default value)
```

This feature could be game-changing!

Thank you very much for your work, @keithmifsud!

Best,   
T

**Comment by keithmifsud** [comment]
Hi @xplosionmind ,

thank you for the suggestion :smile: 

Sorry, but this one is not possible as the parsing gets done after the HTML generation irrelevant to the initial format (md).

I have to close this suggestion but please feel at ease to re-open it with a PR if you've figured a wat to get around this :wink:
