### ISSUE TITLE
Plugin not working unless the gem is added to the group :jekyll_plugins section

### ISSUE THREAD

**Issue by lucius-asclepius** [keithmifsud/jekyll-target-blank#63]
Hi, I'm using the [minimal-mistakes](https://github.com/mmistakes/minimal-mistakes) template and I don't know if it's something specific to that, but `jekyll-target-blank` didn't work by just adding it to the end of the `Gemfile`; instead, I had to add it to the `group :jekyll_plugins` section. I spent 30 minutes figuring this out so I thought it would be useful to open an issue so that it's noted.

```
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jekyll-feed"
  gem "jemoji"
  gem "jekyll-include-cache"
  gem "jekyll-algolia"
  gem "jekyll-target-blank"
end

gem "commonmarker", "~> 0.23.4"
gem "racc", "~> 1.6"
gem "unf_ext", "~> 0.0.8"
gem "minimal-mistakes-jekyll"
gem "webrick", "~> 1.7"
```

Maybe `README.md` should write something like this?

> Add the following to your site's Gemfile (into the `group :jekyll_plugins` section if you have one):
> 
> ```
> gem 'jekyll-target-blank'
> ```

**Comment by benfwalla** [comment]
I love you!

**Comment by itsmevictor** [comment]
I'm using the [Academic Pages](https://github.com/academicpages/academicpages.github.io) template which is a fork of the minimal-mistakes one, but it does not appear to be working for me. 

I added this to my Gemfile:
```
# If you have any plugins, put them here!
group :jekyll_plugins do
  # gem "jekyll-archives"
  gem "jekyll-feed"
  gem 'jekyll-sitemap'
  gem 'hawkins'
  gem "webrick", "~> 1.8"
  gem "jekyll-target-blank"
end
```

and that to my `_config.yml`: 
```
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-target-blank
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
```
but links still open on the same page. The weird thing is that when I test my website with `bundle exec jekyll serve`, the plugin works correctly, but not on the Github Pages that hosts my website. 

Any help is appreciated!

**Comment by keithmifsud** [comment]
Hi @itsmevictor and @lucius-asclepius, We did try (several times now) to get the plugin approved by GitHub and added to the whitelist. Unfortunately, we never received a reply.

You'll need to build your site locally and deploy it afterwards.
