### ISSUE TITLE
Not working when URL constructed from site data

### ISSUE THREAD

**Issue by lifan0127** [keithmifsud/jekyll-target-blank#69]
@keithmifsud Thanks for creating this plugin! It works well when a URL is hard-coded in document. But I couldn't make it work if the URL comes from a variable within site data. For example:

```md
[Google](https://google.com)
[Google]({{ site.data.google.url }})
<a href="{{ site.data.google.url }}">Google</a>
```

Only the first URL is rendered with target="_blank"

![image](https://github.com/keithmifsud/jekyll-target-blank/assets/7218193/bb3b2de7-1fc7-43ec-b6f3-2ead27de3502)

Do you have any advice? Thanks again!

**Comment by prplecake** [comment]
I suspect the lack of a protocol is causing jekyll-target-blank to ignore that link:
https://github.com/keithmifsud/jekyll-target-blank/blob/b8c7fb51f8d101203f6c0aac453196a81f3f51d7/lib/jekyll-target-blank.rb#L194-L198

Does adding a protocol make any difference?

**Comment by lifan0127** [comment]
Hi @prplecake  Thank you for your prompt response. That was indeed the problem. Appreciate your help!

**Comment by keithmifsud** [comment]
Thank you for asking @lifan0127, and thank you @prplecake, for your help :)
