### ISSUE TITLE
Release version 1.1

### ISSUE THREAD

**Issue by keithmifsud** [keithmifsud/jekyll-target-blank#8]
- [x] Complete all security issues.
- [x] Complete all new features.
- [x] Refactor code:
  - [x] Consolidate the methods requiring config value checks.
- [x] Complete all documentation tasks.
  - [x] Grammar check!
- [x] Run Integraion tests for all issues:
  - [x] issue 1...
- [x] Publish the new version.

**Comment by keithmifsud** [comment]
@buren I publicly thanked you here https://keith-mifsud.me/projects/jekyll-target-blank Thank you for your contributions.

**Comment by buren** [comment]
@keithmifsud cool! 🌟
